const BASE_URL = process.env.REACT_APP_BASE_URL;
const REACT_APP_BACKEND_URL = process.env.REACT_APP_BACKEND_URL;
const LOGIN_URL = `${process.env.REACT_APP_LOGIN_URL}/login`;
const REACT_APP_LOGIN_URL = process.env.REACT_APP_LOGIN_URL;
const REACT_APP_GOOGLE_API_KEY = process.env.REACT_APP_GOOGLE_API_KEY;


export { BASE_URL, LOGIN_URL, REACT_APP_BACKEND_URL, REACT_APP_LOGIN_URL, REACT_APP_GOOGLE_API_KEY };

